### ISSUE TITLE
[Win 7] Build troubles

### ISSUE THREAD

**Issue by maraev** [CryptonZylog/carbonator#10]
Hello!
I tried to use that for my Win7 laptop and got any troubles with building like below:

> Log.cs(2,7): error CS0246: The type or namespace name 'log4net' could not be fo
> und (are you missing a using directive or an assembly reference?) [C:\Program F
> iles\Carbonator\Carbonator\Carbonator.csproj]
> Log.cs(3,7): error CS0246: The type or namespace name 'log4net' could not be fo
> und (are you missing a using directive or an assembly reference?) [C:\Program F
> iles\Carbonator\Carbonator\Carbonator.csproj]
> Log.cs(26,24): error CS0246: The type or namespace name 'ILog' could not be fou
> nd (are you missing a using directive or an assembly reference?) [C:\Program Fi
> les\Carbonator\Carbonator\Carbonator.csproj]

Unfortunatelly I'm very new with any compiling and stuck here. Could you please give any advice how to fix it?

**Comment by CryptonZylog** [comment]
Are you compiling via MSBuild or Visual Studio? If using just MSBuild, you also need to install [nuget command-line utility](https://docs.nuget.org/consume/installing-nuget) and then do ``nuget restore Carbonator.sln``. This will download log4net package and let you compile. This is automatic in VS (2013/2015)

~~~

Чем компилируете? В Вижле или мсбилде? Если в мсбилде, то надо еще скачать/установить nuget (система управления пакетами), затем выполнить ``nuget restore Carbonator.sln`` и потом уже компилировать проект. В вижле это делается автоматически (2013/2015).
