### ISSUE TITLE
The service installer of the release Crypton.Carbonator-v1.5.zip is broken

### ISSUE THREAD

**Issue by klaffke** [CryptonZylog/carbonator#12]
Starting install-service.cmd on WIndows 8.1 returns the following error message (pardon the german, translation below):

C:\Users\X\Desktop\Carbonator.v1.5.Release>install-service.cmd
Microsoft (R) .NET Framework-Installationsprogramm, Version 4.0.30319.33440
Copyright (C) Microsoft Corporation. Alle Rechte vorbehalten.

Beim Initialisieren der Installation ist eine Ausnahme aufgetreten:
System.IO.FileLoadException: Die Datei oder Assembly "file:///C:\Users\X\De
sktop\Carbonator.v1.5.Release\Crypton.Carbonator.exe" oder eine Abhängigkeit dav
on wurde nicht gefunden. Der Vorgang wird nicht unterstützt. (Ausnahme von HRESU
LT: 0x80131515)

Translation:
An exception occurred during initialisation of the installation: System.IO.FileLoadException: The file or Assembly "file:///C:\Users\X\Desktop\Carbonator.v1.5.Release\Crypton.Carbonator.exe" or one of its dependencies couldn't be found. This process is not supported. (exception from HRESU
LT: 0x80131515)

Compiling Carbonator using Visual Studio 2013 worked, though.

**Comment by sapozhnikovay** [comment]
Windows 2012 R2, Windows 8.1 --- 1.5 release installer - all OK.
All files from archive copied to C:\.... - Location, accessible to Network Service account. !Not in user profile folders!
Then started installer batch file from elevated command promt ("Run As administrator").

Service deletion also worked ok (ensure to close all MMC windows first).

**Comment by klaffke** [comment]
You're right, I've extracted the installer to the Desktop folder of my user account. The compile output was saved to another drive instead.

Maybe you could extend the sentence

"Copy binaries to wherever directory you want application to run from"

to

Copy binaries to wherever directory you want application to run from. Note that if you want to install Carbonator as a service, don't copy it into a user profile folder.

or similar.

Thanks for the response!
