### ISSUE TITLE
RegEx pattern support

### ISSUE THREAD

**Issue by GriffReborn** [CryptonZylog/carbonator#15]
Hi,

What level of RegEx support is there in the new wildcard functionality for loading instances?  I'm trying to load all network adapters, but miss out those I know will just fill the database with null/bad data.  So instead of .+ as per the example in the config file, I'm using:

``.*^((?!.*6to4.*)(?!.*Local.*)(?!.*WAN.*)(?!.*isatap.*)(?!.*Kernel.*)(?!.*Test.*)).*(\n)``

But it doesn't work.  Not errors returned, but no data uploaded.  I also tried without the (\n)

According to RegExr, this should work.  Am I doing it wrong? Is there anything else I need to do? Or is this a case of there not been 100% support for RegEx?

Thanks!

![chrome_2016-07-06_15-02-09](https://cloud.githubusercontent.com/assets/11091780/16620513/a976f872-438a-11e6-93b4-afd40b04c469.png)

**Comment by GriffReborn** [comment]
The line in my config is :
`
<add path="PerfMon.MES.%HOST%.NetworkAdapter.BytesTotalSec.%COUNTER_INSTANCE%" category="Network Adapter" counter="Bytes Total/sec" instance=".*^((?!.*6to4.*)(?!.*Local.*)(?!.*WAN.*)(?!.*isatap.*)(?!.*Kernel.*)(?!.*Test.*)).*(\n)"/>`

**Comment by CryptonZylog** [comment]
FYI, I am getting an exception that 'Network Adapter' category does not exist, have you tried 'Network Interface'?

**Comment by GriffReborn** [comment]
I don't know what's different this morning, but the RegEx without the (/n) is working for me now.

FWIW in both cases I was seeing "Loaded 1 watchers".  So it was loading even though it was matching nothing.

Screengrab shows difference between .+ and the wildcard.  I've changed it slightly to add both types of ISATAP interface.

Sorry to have taken your time up with this, but hopefully at least this RegEx is useful for other people!

For reference, here's how that working section looks now :

```
    <counters>
	  <add path="PerfMon.MES.%HOST%.NetworkAdapter.BytesTotalSec.%COUNTER_INSTANCE%" category="Network Adapter" counter="Bytes Total/sec" instance=".*^((?!.*6to4.*)(?!.*Local.*)(?!.*WAN.*)(?!.*isatap.*)(?!.*ISATAP.*)(?!.*Kernel.*)(?!.*Test.*)).*"/>
	</counters>
```


![paintdotnet_2016-07-07_09-15-38](https://cloud.githubusercontent.com/assets/11091780/16646695/63f9c128-4423-11e6-91e7-84b5a9dbfa35.png)
