### ISSUE TITLE
Issue with metric value on non en_US systems

### ISSUE THREAD

**Issue by jbsarrodie** [CryptonZylog/carbonator#2]
Hi,

First and before all, thank you for your work!

I've just done some tests, and found that on a french system, the metric value is sent to the graphite server using a comma instead of a dot, making it rejected.

Would it be possible to change this so that even on non en_US systems a dot would be used for metric?

Regards

**Comment by CryptonZylog** [comment]
You can specify the metric path in ``app.config``. The path attribute is the final metric path that will be sent over to carbon, just ensure there aren't any commas in the path.

```
<add path="my.data.perf.%HOST%.memAvailable" category="Memory" counter="Available Bytes" instance="" />
```

**Comment by jbsarrodie** [comment]
Hi,

I receive an automatic mail from GitHub related to a response I cannot see here.

Anyway, the issue is not on the metric name, but on the metric value, leading to something like that: `path.of.my.metric 123,12 timestamp`

To my knowledge (but I have check in teh code itself) there's no way to tune the metric value. It seems to me like this counter value is converted to text somewhere and then send as is to graphite.

But I may be false

Regards

**Comment by CryptonZylog** [comment]
Right, I just realised that after I submitted the original comment.

I think the issue is in the string formatting that occurs in [CollectedMetric.cs](https://github.com/CryptonZylog/carbonator/blob/master/Carbonator/CollectedMetric.cs) (ToString method).

A fix is possible by using InvariantCulture.
