### ISSUE TITLE
Is this still under dev?  Q about Config Dir?

### ISSUE THREAD

**Issue by seanvree** [CryptonZylog/carbonator#24]
So I'm not new to building applications using VS. 

I ran the build, and as your instructions states, it puts all the binaries in the /release folder. Great.

I can run Crypton.Carbonator.exe --console --verbose and I will see minimal stats populating. 

Where I"m confused is when you state "/configuration/carbonator/graphite" folder.  Where is this folder?  It wasn't built when I compiled.  the closest I get is the files from this REPO which are /config/FILE.cs, etc.  I see the crypton.carbonator.exe.config file in the root dir, but no .XML files.

What am I missing?

**Comment by CryptonZylog** [comment]
That is not a folder path, but an XPath. The .config file is the XML configuration (which you can open with any text editor).

The path basically means <configuration> element, then 'carbonator' element under it, then 'graphite'.



13 мая 2017 г. 8:29:55 GMT-07:00, seanvree <notifications@github.com> пишет:
>So I'm not new to building applications using VS. 
>
>I ran the build, and as your instructions states, it puts all the
>binaries in the /release folder. Great.
>
>I can run Crypton.Carbonator.exe --console --verbose and I will see
>minimal stats populating. 
>
>Where I"m confused is when you state
>"/configuration/carbonator/graphite" folder.  Where is this folder?  It
>wasn't built when I compiled.  the closest I get is the files from this
>REPO which are /config/FILE.cs, etc.  I see the
>crypton.carbonator.exe.config file in the root dir, but no .XML files.
>
>What am I missing?  
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/CryptonZylog/carbonator/issues/24

-- 
Простите за краткость, создано в K-9 Mail.

**Comment by seanvree** [comment]
Got it. Thanks.
