### ISSUE TITLE
Adding support for domain name.

### ISSUE THREAD

**Issue by GriffReborn** [CryptonZylog/carbonator#6]
Firstly, just wanted to say what a fantastic project this is. I'm finding it very useful in our production environment.

Secondly, that I'm totally new to C# and GitHub, so bear with me!

We have multiple domains, often with same hostnames, so I added simple support for domains:

Inserted line 10
using System.DirectoryServices.ActiveDirectory;

Altered line 187 (188 after insert)
                    .Replace("%HOST%", Environment.MachineName).Replace("%DOMAIN%", Domain.GetComputerDomain().Name);

While this addition works perfectly, replacing %DOMAIN% with the name of the computers domain, it breaks when a server is not domain joined. So some exception handling is required which is currently beyond my skill level.

Any suggestions? (should I "pull" this?)

**Comment by CryptonZylog** [comment]
This should be possible. I've been thinking about allowing system environment variables to be used in metric path templates actually. Not sure if I will make it A/D aware, since ``Environment`` static class provides a ``UserDomainName`` property.

**Comment by GriffReborn** [comment]
Thanks for the swift response!

As far as I could make out, the domain isn't in an environment anywhere.  The UserDomainName is exactly that, the domain of the user (i.e. not the machine).

The only way I could find was by using System.DirectoryService.ActiveDirectory, but like I say, that will throw an exception on a workgroup machine.

**Comment by GriffReborn** [comment]
I've continued looking into this.  I can't find any other way to get the machines domain name than by using System.DirectoryService.ActiveDirectory.   I think this just needs to happen further up and be more elegantly handled so that if it throws an exception, then we know that the machine is not AD joined.

**Comment by CryptonZylog** [comment]
Resolved in v1.5

**Comment by GriffReborn** [comment]
Is this resolved though?  Original request was for AD domain and this method does not work with AD domain.

**Comment by CryptonZylog** [comment]
[This](https://github.com/CryptonZylog/carbonator/blob/master/Carbonator/CounterWatcher.cs#L225) method resolves the Windows domain when you specify a %DOMAIN% variable in the metric path. Does it not work for you?
